### ISSUE TITLE
could u share the VTK data you used?

### ISSUE THREAD

**Issue by stephenkung** [m-pilia/volume-raycasting#2]
I tried some other VTK data, and the program didn't work. So I thought to try your orignal data may work, could u share a link to the foot scan VTK data? Thanks a lot!

**Comment by m-pilia** [comment]
Hi, you can find the example data [here](https://github.com/cg2017-uu/assignment4/tree/master/raycaster/data). The reader in this repo is only for demonstration, and it only supports VTK structured points legacy in binary format. You can write your own reader/converter if your data has a different format.
